config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessionns do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end



  # get 'sessionns/index'
  # get 'sessionns/create'
  # get 'sessionns/destroy'
  # get 'sessionns/new'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'store#index',  as: 'store_index'
end

app/models/admin.rb
class Admin < ApplicationRecord




  def what_type
    type
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
exiexi  belongs_to :doctor
  belongs_to :patient
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)

    current_item = line_items.find_by(product_id: product)
    if current_item
       current_item.counter =  current_item.counter + 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item

  end


  def total_amount
    # line_items
      line_items.to_a.sum {|item|  item.total_price}
  end

  def show
    line_items.each do |item|

      item
    end

  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many  :patients, through: :appointments
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true



  def total_price
     product.price * counter
  end






end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, :email, :address, presence: true
  # validates :pay_type, inclusion: pay_types.keys
  #
  has_many :line_items, dependent: :destroy

  enum pay_type: {
    # "Check"  => 0,
    # "Credit Card"  => 1,
    # "Purchase Order"  => 1,exit
    #
    Check: 19, Credit:2, Purchase:3
  }

  def output
    name
  end


  def add_line_item_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end



  end

end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :destroy

  validates :title, :description, :image_url, presence:{message: "%{value} must be present"}
  validates :title, uniqueness:{case_sensitive: false},length:{in: 5..20}
  validates :image_url, allow_blank: true,format:{with: %r{\.(gif|jpeg|png|jpg)\z}i,
                                                  message: "must be image extenssinom"}
  validates :price ,numericality: {greater_than: 0.0}

end

app/models/super_admin.rb
class SuperAdmin < Admin

end

app/models/user.rb
class User < ApplicationRecord
   validates :name, presence:true, uniqueness: true


   # validates  :user_type, presence:true, inclusion: user_types.keys


   has_secure_password




   enum user_types: { admins: 1, users: 2 }



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authorize
  include CurrentCart


  before_action :set_product, only: %i[ show edit update destroy ]

  before_action :set_cart

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }

        @products = Product.all.order(:title)
        ActionCable.server.broadcast 'products', { product: @product }






      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/email_helper.rb
module EmailHelper

  def email_image_tag(image, **options)
    attachments[image] = File.read(Rails.root.join("app/assets/images/#{image}"))
    image_tag attachments[image].url, **options
  end


end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessionns_helper.rb
module SessionnsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/try_helper.rb
module TryHelper
  def output
      "this is from output helper"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows:10, cols:60 %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
 <%= sanitize(truncate("<h1>i love bangladesh</h1>"),length: 10)%>
<h1>Products</h1>

<table>
  <thead>
<!--    <tr>-->
<!--      <th>Title</th>-->
<!--      <th>Description</th>-->
<!--      <th>Price</th>-->
<!--      <th>Image url</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr class="<%= cycle('list_line_odd','list_line_even') %>">
        <td class="image">
          <%=   image_tag("#{product.image_url}",alt: "not found", class: 'list_image')%>
        </td>

        <td class="description">
           <h1><%= product.title %></h1>
           <p>
           <%= truncate(strip_tags(product.description), length: 80) %>
           </p>
        </td>

<!--        <td>-->
          <%#= product.price %>
<!--        </td>-->

        <td class="actions">
           <ul>
             <li>  <%= link_to 'Show', product %> </li>
             <li> <%= link_to 'Edit', edit_product_path(product) %> </li>
             <li>  <%= link_to 'Destroy',product_url(product), method: :delete, data: { confirm: 'Are you sure?' } %></li>
           </ul>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>