config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessionns do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end



  # get 'sessionns/index'
  # get 'sessionns/create'
  # get 'sessionns/destroy'
  # get 'sessionns/new'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'store#index',  as: 'store_index'
end

app/models/admin.rb
class Admin < ApplicationRecord




  def what_type
    type
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
exiexi  belongs_to :doctor
  belongs_to :patient
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)

    current_item = line_items.find_by(product_id: product)
    if current_item
       current_item.counter =  current_item.counter + 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item

  end


  def total_amount
    # line_items
      line_items.to_a.sum {|item|  item.total_price}
  end

  def show
    line_items.each do |item|

      item
    end

  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many  :patients, through: :appointments
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true



  def total_price
     product.price * counter
  end






end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, :email, :address, presence: true
  # validates :pay_type, inclusion: pay_types.keys
  #
  has_many :line_items, dependent: :destroy

  enum pay_type: {
    # "Check"  => 0,
    # "Credit Card"  => 1,
    # "Purchase Order"  => 1,exit
    #
    Check: 19, Credit:2, Purchase:3
  }

  def output
    name
  end


  def add_line_item_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end



  end

end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :destroy

  validates :title, :description, :image_url, presence:{message: "%{value} must be present"}
  validates :title, uniqueness:{case_sensitive: false},length:{in: 5..20}
  validates :image_url, allow_blank: true,format:{with: %r{\.(gif|jpeg|png|jpg)\z}i,
                                                  message: "must be image extenssinom"}
  validates :price ,numericality: {greater_than: 0.0}

end

app/models/super_admin.rb
class SuperAdmin < Admin

end

app/models/user.rb
class User < ApplicationRecord
   validates :name, presence:true, uniqueness: true


   # validates  :user_type, presence:true, inclusion: user_types.keys


   has_secure_password




   enum user_types: { admins: 1, users: 2 }



end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart

  before_action :set_cart, only: %i[ create ]
  before_action :set_line_item, only: %i[ show edit update destroy ]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create

    product = Product.find(params[:product_id])

    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html {  redirect_to  store_index_url, notice:'line item successfully created' }
        format.js
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy

    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/email_helper.rb
module EmailHelper

  def email_image_tag(image, **options)
    attachments[image] = File.read(Rails.root.join("app/assets/images/#{image}"))
    image_tag attachments[image].url, **options
  end


end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessionns_helper.rb
module SessionnsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/try_helper.rb
module TryHelper
  def output
      "this is from output helper"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr id="cart-product-<%= line_item.product.id %>">

  <td class="quantity"><%= line_item.counter %></td>

  <td class="title"><%= line_item.product.title %></td>


  <td class="price"><%= line_item.total_price %></td>

</tr>

app/views/line_items/_show.html.erb
<p id="notice"><%= notice %></p>

<h1>your Pragmatic card </h1>
 <%= params %>


<%# @cart do  |item|%>

<!--    <p><%#= item.product.title %></p>-->
  <%# end %>
<!--<p>-->
<!--  <strong>Product:</strong>-->
  <%#= @line_item.product.title %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Cart:</strong>-->
  <%#= @line_item.cart %>
<!--</p>-->

<%= link_to 'Edit', edit_line_item_path%> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/create.js.erb
alert("new product add in your cart")
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product.title %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<h1>your Pragmatic card </h1>
 <%= params %>


<%# @cart do  |item|%>

<!--    <p><%#= item.product.title %></p>-->
  <%# end %>
<!--<p>-->
<!--  <strong>Product:</strong>-->
  <%#= @line_item.product.title %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Cart:</strong>-->
  <%#= @line_item.cart %>
<!--</p>-->

<%= link_to 'Edit', edit_line_item_path%> |
<%= link_to 'Back', line_items_path %>