config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessionns do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end



  # get 'sessionns/index'
  # get 'sessionns/create'
  # get 'sessionns/destroy'
  # get 'sessionns/new'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'store#index',  as: 'store_index'
end

app/models/admin.rb
class Admin < ApplicationRecord




  def what_type
    type
  end


end

app/models/appointment.rb
exiexi  belongs_to :doctor
  belongs_to :patient
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)

    current_item = line_items.find_by(product_id: product)
    if current_item
       current_item.counter =  current_item.counter + 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item

  end


  def total_amount
    # line_items
      line_items.to_a.sum {|item|  item.total_price}
  end

  def show
    line_items.each do |item|

      item
    end

  end

end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many  :patients, through: :appointments
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  belongs_to :order, optional: true



  def total_price
     product.price * counter
  end






end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, :email, :address, presence: true
  # validates :pay_type, inclusion: pay_types.keys
  #
  has_many :line_items, dependent: :destroy

  enum pay_type: {
    # "Check"  => 0,
    # "Credit Card"  => 1,
    # "Purchase Order"  => 1,exit
    #
    Check: 19, Credit:2, Purchase:3
  }

  def output
    name
  end


  def add_line_item_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end



  end

end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :appointments
  has_many :doctors
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items, dependent: :destroy

  validates :title, :description, :image_url, presence:{message: "%{value} must be present"}
  validates :title, uniqueness:{case_sensitive: false},length:{in: 5..20}
  validates :image_url, allow_blank: true,format:{with: %r{\.(gif|jpeg|png|jpg)\z}i,
                                                  message: "must be image extenssinom"}
  validates :price ,numericality: {greater_than: 0.0}

end

app/models/super_admin.rb
class SuperAdmin < Admin

end

app/models/user.rb
class User < ApplicationRecord
   validates :name, presence:true, uniqueness: true


   # validates  :user_type, presence:true, inclusion: user_types.keys


   has_secure_password




   enum user_types: { admins: 1, users: 2 }



end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/email_helper.rb
module EmailHelper

  def email_image_tag(image, **options)
    attachments[image] = File.read(Rails.root.join("app/assets/images/#{image}"))
    image_tag attachments[image].url, **options
  end


end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessionns_helper.rb
module SessionnsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/try_helper.rb
module TryHelper
  def output
      "this is from output helper"
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>welcome to admion panel</h1>

<p>

  it's <%= Time.now %>

  we have <%= pluralize(@total_orders.count,'order') %>


</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>



<header class="main">
  <%= image_tag 'logo.svg', alt: 'logo not found'%>
  <h1><%= @page_title%></h1>
</header>


<section class="content">

  <nav class="side_nav">

    <%  if @cart %>

      <div id="cart" class="carts">

        <%= render @cart %>

      </div>

    <% end %>



    <ul>
      <li><a href='/'>Home</a></li>
      <li><a  href='/'>Questions</a></li>
      <li><a  href='/'>News</a></li>
      <li><a  href='/'>Contact</a></li>
    </ul>


    <ul>
      <li><%= link_to 'Orders', orders_path %></li>
      <li><%= link_to 'Orders', products_path %></li>
      <li><%= link_to 'Orders', users_path %></li>
      <li><%=  button_to  'Logout' , logout_path , method: :delete, data: { confirm: 'do uy want to log out'} %></li>
    </ul>


  </nav>



  <main class=' <%= controller.controller_name  %>'>

    <h1>admin layoout</h1>
    <%= yield %>

  </main>

</section>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <header class="main">
      <%= image_tag 'logo.svg', alt: 'logo not found'%>
      <h1><%= @page_title%></h1>
     </header>
    
    <section class="content">
       
       <nav class="side_nav">

       <%  if @cart %>

       <div id="cart" class="carts">

         <%= render @cart %>

       </div>

         <% end %>



         <ul>
          <li><a href='/'>Home</a></li>
          <li><a  href='/'>Questions</a></li>
          <li><a  href='/'>News</a></li>
          <li><a  href='/'>Contact</a></li>
         </ul>


         <ul>
           <li><%= link_to 'Orders', orders_path %></li>
           <li><%= link_to 'Orders', products_path %></li>
           <li><%= link_to 'Orders', users_path %></li>
           <li><%=  button_to  'Logout' , logout_path , method: :delete, data: { confirm: 'do uy want to log out'} %></li>
         </ul>


       </nav>



       <main class=' <%= controller.controller_name  %>'>

          <%= yield %>

      </main>
    
    </section>
  
  </body>
 
</html>